gateway:
  - namespace: argocd
    ingress:
      - name: istio-ingressgateway
        selector:
          service.istio.io/canonical-name: istio-ingressgateway
        ports:
          - name: http
            number: 80
            protocol: HTTP
            hosts:
            - '"*"'
          - protocol: HTTPS
            number: 443
            name: https
            tls:
              credentialName: argocd-server-tls
              mode: SIMPLE
              maxProtocolVersion: TLSV1_3
              minProtocolVersion: TLSV1_2
              cipherSuites:
                - ECDHE-ECDSA-AES128-GCM-SHA256
                - ECDHE-RSA-AES128-GCM-SHA256
                - ECDHE-ECDSA-AES128-SHA
                - AES128-GCM-SHA256
                - AES128-SHA
                - ECDHE-ECDSA-AES256-GCM-SHA384
                - ECDHE-RSA-AES256-GCM-SHA384
                - ECDHE-ECDSA-AES256-SHA
                - AES256-GCM-SHA384
                - AES256-SHA
            hosts:
              - '"*"'
    egress:
      - name: istio-egressgateway
        selector:
          service.istio.io/canonical-name: istio-egressgateway
        ports:
          - protocol: TLS
            number: 443
            name: tls
            tls:
              mode: PASSTHROUGH
            hosts:
              - '"*"'
  - namespace: jenkins
    ingress:
      - name: istio-ingressgateway
        selector:
          service.istio.io/canonical-name: istio-ingressgateway
        ports:
          - name: http
            number: 80
            protocol: HTTP
            hosts:
            - '"*"'
          - protocol: HTTPS
            number: 443
            name: https
            tls:
              credentialName: jenkins-server-tls
              mode: SIMPLE
              maxProtocolVersion: TLSV1_3
              minProtocolVersion: TLSV1_2
              cipherSuites:
                - ECDHE-ECDSA-AES128-GCM-SHA256
                - ECDHE-RSA-AES128-GCM-SHA256
                - ECDHE-ECDSA-AES128-SHA
                - AES128-GCM-SHA256
                - AES128-SHA
                - ECDHE-ECDSA-AES256-GCM-SHA384
                - ECDHE-RSA-AES256-GCM-SHA384
                - ECDHE-ECDSA-AES256-SHA
                - AES256-GCM-SHA384
                - AES256-SHA
            hosts:
              - '"*"'
    egress:
      - name: istio-egressgateway
        selector:
          service.istio.io/canonical-name: istio-egressgateway
        ports:
          - protocol: TLS
            number: 443
            name: tls
            tls:
              mode: PASSTHROUGH
            hosts:
              - '"*"'
  - namespace: demo
    ingress:
      - name: istio-ingressgateway
        selector:
          service.istio.io/canonical-name: istio-ingressgateway
        ports:
          - name: http
            number: 80
            protocol: HTTP
            hosts:
            - '"*"'
          - protocol: HTTPS
            number: 443
            name: https
            tls:
              credentialName: demo-server-tls
              mode: SIMPLE
              maxProtocolVersion: TLSV1_3
              minProtocolVersion: TLSV1_2
              cipherSuites:
                - ECDHE-ECDSA-AES128-GCM-SHA256
                - ECDHE-RSA-AES128-GCM-SHA256
                - ECDHE-ECDSA-AES128-SHA
                - AES128-GCM-SHA256
                - AES128-SHA
                - ECDHE-ECDSA-AES256-GCM-SHA384
                - ECDHE-RSA-AES256-GCM-SHA384
                - ECDHE-ECDSA-AES256-SHA
                - AES256-GCM-SHA384
                - AES256-SHA
            hosts:
              - '"*"'
    egress:
      - name: istio-egressgateway
        selector:
          service.istio.io/canonical-name: istio-egressgateway
        ports:
          - protocol: TLS
            number: 443
            name: tls
            tls:
              mode: PASSTHROUGH
            hosts:
              - '"*"'
egress:
  - namespace: default
    rules:
      - protocol: https
        port: 443
        destination: istio-egressgateway.istio-system.svc.cluster.local
        gateway: istio-system/istio-egressgateway
        hosts:
          - "vnexpress.net"
  - namespace: argocd
    rules:
      - protocol: https
        port: 443
        destination: istio-egressgateway.istio-system.svc.cluster.local
        gateway: istio-egressgateway
        hosts:
          - "vnexpress.net"
          - "github.com"
          - "raw.githubusercontent.com"
  - namespace: jenkins
    rules:
      - protocol: https
        port: 443
        destination: istio-egressgateway.istio-system.svc.cluster.local
        gateway: istio-egressgateway
        hosts:
          - "sg.mirror.servanamanaged.com"
          - "mirror.freedif.org"
          - "jenkins.io"
          - "updates.jenkins.io"
virtualService:
  enabled: false
