{{- if .Values.volume }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.volume.name }}
spec:
  accessModes:
    - ReadOnlyMany
  capacity:
    storage: {{ .Values.volume.capacity }}
  hostPath:
    path: "{{ .Values.volume.hostPath }}/{{ .Values.volume.name }}"
  storageClassName: ""
{{- end -}}