{{- if .Values.volume }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.volume.name }}
spec:
  accessModes:
    - ReadOnlyMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.volume.capacity }}
  storageClassName: {{ .Values.volume.storageClassName }}
{{- end -}}