IMAGE_NAME = "ubuntu/xenial64"
MASTER_NODE = 3
N = 2
ENV["LC_ALL"] = "en_US.UTF-8"
KUBELET_VERSION="1.20.4-00"
KUBEADM_VERSION="1.20.4-00"
KUBECTL_VERSION="1.20.4-00"

$script = <<-'SCRIPT'
echo 192.168.50.10 lb-master >> /etc/hosts
echo 192.168.50.11 master-1 >> /etc/hosts
echo 192.168.50.12 master-2 >> /etc/hosts
echo 192.168.50.13 master-3 >> /etc/hosts
SCRIPT

$lb = <<-'SCRIPT'
apt -y install nginx
cat /tmp/nginx_tcp_proxy.conf| tee -a /etc/nginx/nginx.conf
systemctl restart nginx
SCRIPT

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false
    config.vm.provider "virtualbox" do |v|
        v.memory = 2048
        v.cpus = 2
        v.linked_clone = true
    config.vbguest.auto_update = false
    # config.vbguest.installer_options = { allow_kernel_upgrade: true }
    # config.vbguest.installer_arguments = ['--nox11']
    end

    (1..MASTER_NODE).each do |i|
        config.vm.define "master-#{i}" do |master|
            master.vm.box = IMAGE_NAME
            master.vm.network "private_network", ip: "192.168.50.#{i + 10}"
            master.vm.hostname = "etcd-master-#{i}"

            master.vm.provision "shell",  inline: $script
            master.vm.provision "ansible" do |ansible|
                ansible.playbook = "../Vagrant/kubernetes-setup/master-playbook.yml"
                ansible.extra_vars = {
                    node_ip: "192.168.50.#{i + 10}",
                    kubelet_version: KUBELET_VERSION,
                    kubeadm_version: KUBEADM_VERSION,
                    kubectl_version: KUBECTL_VERSION,
                }
                ansible.tags = "bootstrap"
            end
        end
    end

    config.vm.define "lb-master" do |lb|
        lb.vm.box = IMAGE_NAME
        lb.vm.network "private_network", ip: "192.168.50.10"
        lb.vm.hostname = "lb-master"
        lb.vm.provider "virtualbox" do |v|
            v.memory = 512
            v.cpus = 1
        end
        lb.vm.provision "file", source: "nginx_tcp_proxy.conf", destination: "/tmp/nginx_tcp_proxy.conf"
        lb.vm.provision "shell", inline: $script
        lb.vm.provision "shell", inline: $lb
    end

    (1..N).each do |i|
        config.vm.define "node-#{i}" do |node|
            node.vm.box = IMAGE_NAME
            node.vm.network "private_network", ip: "192.168.50.#{(i + 1) * 10}"
            node.vm.hostname = "node-#{i}"
            node.vm.provision "ansible" do |ansible|
                ansible.playbook = "../Vagrant/kubernetes-setup/node-playbook.yml"
                ansible.extra_vars = {
                    node_ip: "192.168.50.#{(i + 1) * 10}",
                    kubelet_version: KUBELET_VERSION,
                    kubeadm_version: KUBEADM_VERSION,
                    kubectl_version: KUBECTL_VERSION,
                }
                ansible.tags = "bootstrap"
            end
        end
    end
end