apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: cka
spec: {}
status: {}
---
apiVersion: v1
kind: LimitRange
metadata:
  name: mem-limit-range
  namespace: cka
spec:
  limits:
  - default:
      memory: 512Mi
    defaultRequest:
      memory: 64Mi
    type: Container
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: pv-quota
  namespace: cka
spec:
  hard:
    persistentvolumeclaims: "2"
    services.loadbalancers: "2"
    services.nodeports: "0"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-quota-1
  namespace: cka
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-quota-2
  namespace: cka
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
     storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: busybox
  name: busybox
  namespace: cka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: busybox
    spec:
      containers:
      - command:
        - sleep
        - 1h
        image: busybox
        name: busybox
        volumeMounts:
        - mountPath: "/var/www/html"
          name: mypd
        - mountPath: "/var/www/html2"
          name: mypd2
        resources: {}
      volumes:
        - name: mypd
          persistentVolumeClaim:
            claimName: pvc-quota-1
        - name: mypd2
          persistentVolumeClaim:
            claimName: pvc-quota-2
