IMAGE_NAME = "ubuntu/xenial64"
N = 2
ENV["LC_ALL"] = "en_US.UTF-8"
KUBELET_VERSION="1.21.1-00"
KUBEADM_VERSION="1.21.1-00"
KUBECTL_VERSION="1.21.1-00"
Vagrant.configure("2") do |config|
    config.ssh.insert_key = false
    config.vm.provider "virtualbox" do |v|
        v.memory = 2048
        v.cpus = 2
        v.linked_clone = true
    config.vbguest.auto_update = false
    end

    config.vm.define "k8s-master" do |master|
        master.vm.box = IMAGE_NAME
        master.vm.network "private_network", ip: "192.168.50.10"
        master.vm.hostname = "k8s-master"
        master.vm.provision "ansible" do |ansible|
            ansible.playbook = "kubernetes-setup/master-playbook.yml"
            ansible.extra_vars = {
                node_ip: "192.168.50.10",
                kubelet_version: KUBELET_VERSION,
                kubeadm_version: KUBEADM_VERSION,
                kubectl_version: KUBECTL_VERSION,
            }
        end
    end

    (1..N).each do |i|
        config.vm.define "node-#{i}" do |node|
            node.vm.box = IMAGE_NAME
            node.vm.network "private_network", ip: "192.168.50.#{(i + 1) * 10}"
            node.vm.hostname = "node-#{i}"
            node.vm.provision "ansible" do |ansible|
                ansible.playbook = "kubernetes-setup/node-playbook.yml"
                ansible.extra_vars = {
                    node_ip: "192.168.50.#{(i + 1) * 10}",
                    kubelet_version: KUBELET_VERSION,
                    kubeadm_version: KUBEADM_VERSION,
                    kubectl_version: KUBECTL_VERSION,
                }
            end
        end
    end
end