apiVersion: v1
kind: Pod
metadata:
  name: init-demo
  labels:
    app : init-demo
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: workdir
      mountPath: /usr/share/nginx/html
    resources: {}
  # These containers are run during pod initialization
  initContainers:
  - name: install
    image: busybox
    command:
    - sh
    - -c
    - echo "created by init container" > /work-dir/index.html
    volumeMounts:
    - name: workdir
      mountPath: "/work-dir"
  dnsPolicy: Default
  volumes:
  - name: workdir
    emptyDir: {}
