#Step 1: Install Docker and its dependent components
---
- hosts: all
  become: true
  tasks:
    - name: Load kernel module
      modprobe:
        name: "{{ item }}"
      with_items:
        - overlay
        - br_netfilter
      tags: bootstrap
    - name: Setup kernel
      sysctl:
        name: "{{ item }}"
        value: '1'
        sysctl_set: yes
        state: present
        reload: yes
      with_items:
      - net.bridge.bridge-nf-call-iptables
      - net.ipv4.ip_forward
      - net.bridge.bridge-nf-call-ip6tables
      - net.bridge.bridge-nf-call-arptables
      tags: bootstrap
    - name: Install packages that allow apt to be used over HTTPS
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
      tags: bootstrap
    - name: Add an apt signing key for Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      tags: bootstrap
    - name: Add apt repository for stable version
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
        state: present
      tags: bootstrap
    - name: Install docker and its dependecies
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - docker-ce
          - docker-ce-cli
          - containerd.io
      notify:
        - docker status
      tags: bootstrap
    - name: Replace Docker driver
      copy:
        dest: /etc/docker/daemon.json
        content: |
          {
            "exec-opts": ["native.cgroupdriver=systemd"],
            "log-driver": "json-file",
            "log-opts": {
              "max-size": "100m"
            },
            "storage-driver": "overlay2"
          }
      notify:
        - docker status
      tags: bootstrap
    - name: Add vagrant user to docker group
      user:
        name: vagrant
        group: docker
      tags: bootstrap
    # Step 2: Kubelet will not start if the system has swap enabled, so we are disabling swap using the below code.
    - name: Remove swapfile from /etc/fstab
      mount:
        name: "{{ item }}"
        fstype: swap
        state: absent
      with_items:
        - swap
        - none
      tags: bootstrap
    - name: Disable swap
      command: swapoff -a
      when: ansible_swaptotal_mb > 0
      tags: bootstrap
    #3: Installing kubelet, kubeadm and kubectl using the below code
    - name: Add an apt signing key for Kubernetes
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present
      tags: bootstrap
    - name: Adding apt repository for Kubernetes
      apt_repository:
        repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
        state: present
        filename: kubernetes.list
      tags: bootstrap
    - name: Install Kubernetes binaries
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - kubelet={{ kubelet_version }}
          - kubeadm={{ kubeadm_version }}
          - kubectl={{ kubectl_version }}
      tags: bootstrap
    - name: Configure node ip
      lineinfile:
        path: /etc/default/kubelet
        line: KUBELET_EXTRA_ARGS=--node-ip={{ node_ip }}
        create: yes
      tags: bootstrap
    - name: Fix Kubelet failed to get stats
      copy:
        dest: /etc/systemd/system/kubelet.service.d/11-kubeadm.conf
        content: |
          [Service]
          After=docker.service
      notify:
        - kubelet status
      tags: bootstrap
    #4: Initialize the Kubernetes cluster with kubeadm using the below code (applicable only on master node).
    - name: check existed kubelet config
      stat:
        path: /etc/kubernetes/pki/ca.crt
      register: kubelet
    - debug:
        var: kubelet

    #5: Join the nodes to the Kubernetes cluster using below code.
    - name: Copy the join command to server location
      copy: src=join-command dest=/tmp/join-command.sh mode=0777

    - name: Join the node to cluster
      command: sh /tmp/join-command.sh
      when: kubelet.stat.exists == False
    - name: Configure cgroup driver
      lineinfile:
        path: /var/lib/kubelet/config.yaml
        regexp: '^cgroupDriver*'
        line: 'cgroupDriver: systemd'
      notify:
        - kubelet status
        - docker status
  handlers:
    - name: docker status
      # service: name=docker state=restarted
      systemd:
        name: docker
        state: restarted
        enabled: yes
    - name: kubelet status
      # service: name=kubelet state=restarted
      systemd:
        name: kubelet
        state: restarted
        enabled: yes
