apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "18"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"17"},"creationTimestamp":"2024-07-07T10:29:37Z","generation":56,"labels":{"app":"pause"},"name":"pause","namespace":"default","resourceVersion":"10394","uid":"dd1bd4d5-4b98-4f63-af63-761e0ff419b3"},"spec":{"progressDeadlineSeconds":600,"replicas":3,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"pause"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"annotations":{"kubectl.kubernetes.io/restartedAt":"2024-07-07T22:45:02+07:00"},"creationTimestamp":null,"labels":{"app":"pause"}},"spec":{"containers":[{"image":"registry.k8s.io/pause:3.1","imagePullPolicy":"Always","name":"pause","resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30,"topologySpreadConstraints":[{"labelSelector":{"matchLabels":{"app":"pause"}},"maxSkew":1,"topologyKey":"zone","whenUnsatisfiable":"DoNotSchedule"},{"labelSelector":{"matchLabels":{"app":"pause"}},"maxSkew":1,"topologyKey":"pool","whenUnsatisfiable":"DoNotSchedule"}]}}},"status":{"availableReplicas":3,"conditions":[{"lastTransitionTime":"2024-07-07T15:22:42Z","lastUpdateTime":"2024-07-07T15:45:08Z","message":"ReplicaSet \"pause-f8d95d786\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"},{"lastTransitionTime":"2024-07-07T15:45:28Z","lastUpdateTime":"2024-07-07T15:45:28Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"}],"observedGeneration":56,"readyReplicas":3,"replicas":3,"updatedReplicas":3}}
  creationTimestamp: "2024-07-07T10:29:37Z"
  generation: 57
  labels:
    app: pause
  name: pause
  namespace: default
  resourceVersion: "10532"
  uid: dd1bd4d5-4b98-4f63-af63-761e0ff419b3
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: pause
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2024-07-07T22:45:02+07:00"
      creationTimestamp: null
      labels:
        app: pause
    spec:
      containers:
      - image: registry.k8s.io/pause:3.1
        imagePullPolicy: Always
        name: pause
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app: pause
        maxSkew: 1
        topologyKey: zone
        whenUnsatisfiable: ScheduleAnyway #DoNotSchedule
      - labelSelector:
          matchLabels:
            app: pause
        maxSkew: 1
        topologyKey: pool
        whenUnsatisfiable: ScheduleAnyway #DoNotSchedule
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2024-07-07T15:45:28Z"
    lastUpdateTime: "2024-07-07T15:45:28Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-07-07T15:22:42Z"
    lastUpdateTime: "2024-07-07T15:46:50Z"
    message: ReplicaSet "pause-68495b866d" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 57
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
